- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: Vars/output
    - name: Import Bastion Variable
      include_vars: Vars/Bastion_vars
    - name: create key pair
      ec2_key:
        name: bastionkey
        region: "{{region}}"
      register: keyout
    - name: save private key in a filr
      copy:
        content: "{{keyout.key.private_key}}"
        dest: "./bastionkey.pem"
        mode: 0600
      when: keyout.changed
    - name: Security Group
      ec2_group:
        name: Bastion-host-sg
        description: allow 22 from anywhere
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{myip}}"
      register: bastionsg
    - name: creating Bastion host
      vars:
        ansible_python_interpreter: /usr/bin/python3
      ec2:
        key_name: bastionkey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{Bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: vprofile
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: vprofile
        group_id: "{{bastionsg.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost






