- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Import Variables
      include_vars: Vars/VPC_vars

    - name: create vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        state: "{{state}}"
      register: vpcout
    - debug:
        var: vpcout

    - name: public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{pub1CIDR}}"
        map_public: yes
        resource_tags:
          Name: PubSub1
      register: PubSub1


