- name: generate Artifact , copy Sql files
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: install jdk, maven, git
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven
    - name: clone source code
      git:
        repo: "https://github.com/devopshydclub/vprofile-project.git"
        dest: ./Vprofile-repo
        version: vp-rem
      register: git_status
    - name: mvn install to build artifact
      command: "mvn install"
      args:
         chdir: Vprofile-repo
      when: git_status.changed
      register: mvn_info
    - name: copy artifact to file
      copy:
        src: "{{item}}"
        dest: files/ROOT.war
      with_fileglob: Vprofile-repo/target/*.war
    - name: Copy Sql file
      copy:
        src: Vprofile-repo/src/main/resources/db_backup.sql
        dest: files/db_backup.sql


